export const blitmap: Record<number, { name: string; image: string }> = {
  0: { name: "Genesis", image: "https://api.blitmap.com/v1/png/0" },
  1: { name: "Rose", image: "https://api.blitmap.com/v1/png/1" },
  2: { name: "Boombox", image: "https://api.blitmap.com/v1/png/2" },
  3: { name: "Node", image: "https://api.blitmap.com/v1/png/3" },
  4: { name: "Psychic", image: "https://api.blitmap.com/v1/png/4" },
  5: { name: "Ikura", image: "https://api.blitmap.com/v1/png/5" },
  6: { name: "Edition", image: "https://api.blitmap.com/v1/png/6" },
  7: { name: "Selected", image: "https://api.blitmap.com/v1/png/7" },
  8: { name: "Kraken", image: "https://api.blitmap.com/v1/png/8" },
  9: { name: "Totally", image: "https://api.blitmap.com/v1/png/9" },
  10: { name: "Looney", image: "https://api.blitmap.com/v1/png/10" },
  11: { name: "Atlantis", image: "https://api.blitmap.com/v1/png/11" },
  12: { name: "Otoro", image: "https://api.blitmap.com/v1/png/12" },
  13: { name: "Jupiter", image: "https://api.blitmap.com/v1/png/13" },
  14: { name: "Overloaded", image: "https://api.blitmap.com/v1/png/14" },
  15: { name: "Mask", image: "https://api.blitmap.com/v1/png/15" },
  16: { name: "Vanilla", image: "https://api.blitmap.com/v1/png/16" },
  17: { name: "Tamago", image: "https://api.blitmap.com/v1/png/17" },
  18: { name: "The Cat", image: "https://api.blitmap.com/v1/png/18" },
  19: { name: "Ebi", image: "https://api.blitmap.com/v1/png/19" },
  20: { name: "Eruption", image: "https://api.blitmap.com/v1/png/20" },
  21: { name: "Night Moon", image: "https://api.blitmap.com/v1/png/21" },
  22: { name: "Processing", image: "https://api.blitmap.com/v1/png/22" },
  23: { name: "The Sun", image: "https://api.blitmap.com/v1/png/23" },
  24: { name: "Hillside", image: "https://api.blitmap.com/v1/png/24" },
  25: { name: "Ever Lovin", image: "https://api.blitmap.com/v1/png/25" },
  26: { name: "Cheese", image: "https://api.blitmap.com/v1/png/26" },
  27: { name: "Scramble", image: "https://api.blitmap.com/v1/png/27" },
  28: { name: "Moderator", image: "https://api.blitmap.com/v1/png/28" },
  29: { name: "Swordy", image: "https://api.blitmap.com/v1/png/29" },
  30: { name: "Healtreey", image: "https://api.blitmap.com/v1/png/30" },
  31: { name: "Mageglovey", image: "https://api.blitmap.com/v1/png/31" },
  32: { name: "Feathery", image: "https://api.blitmap.com/v1/png/32" },
  33: { name: "Teddy", image: "https://api.blitmap.com/v1/png/33" },
  34: { name: "Cloudy", image: "https://api.blitmap.com/v1/png/34" },
  35: { name: "Candy", image: "https://api.blitmap.com/v1/png/35" },
  36: { name: "Chessbirdy", image: "https://api.blitmap.com/v1/png/36" },
  37: { name: "Angrybirby", image: "https://api.blitmap.com/v1/png/37" },
  38: { name: "Burgery", image: "https://api.blitmap.com/v1/png/38" },
  39: { name: "Periwinkle", image: "https://api.blitmap.com/v1/png/39" },
  40: { name: "Sprout", image: "https://api.blitmap.com/v1/png/40" },
  41: { name: "Amai", image: "https://api.blitmap.com/v1/png/41" },
  42: { name: "Blit", image: "https://api.blitmap.com/v1/png/42" },
  43: { name: "Rune", image: "https://api.blitmap.com/v1/png/43" },
  44: { name: "Vibe", image: "https://api.blitmap.com/v1/png/44" },
  45: { name: "Ride", image: "https://api.blitmap.com/v1/png/45" },
  46: { name: "Andrei", image: "https://api.blitmap.com/v1/png/46" },
  47: { name: "Soft Boy", image: "https://api.blitmap.com/v1/png/47" },
  48: { name: "Pizza Time", image: "https://api.blitmap.com/v1/png/48" },
  49: { name: "Hot Damn", image: "https://api.blitmap.com/v1/png/49" },
  50: { name: "Everything", image: "https://api.blitmap.com/v1/png/50" },
  51: { name: "Illuminate", image: "https://api.blitmap.com/v1/png/51" },
  52: { name: "Six Months", image: "https://api.blitmap.com/v1/png/52" },
  53: { name: "Mana", image: "https://api.blitmap.com/v1/png/53" },
  54: { name: "Nude", image: "https://api.blitmap.com/v1/png/54" },
  55: { name: "Kabuto", image: "https://api.blitmap.com/v1/png/55" },
  56: { name: "Mori", image: "https://api.blitmap.com/v1/png/56" },
  57: { name: "Hand", image: "https://api.blitmap.com/v1/png/57" },
  58: { name: "Gato", image: "https://api.blitmap.com/v1/png/58" },
  59: { name: "Ear", image: "https://api.blitmap.com/v1/png/59" },
  60: { name: "Eye", image: "https://api.blitmap.com/v1/png/60" },
  61: { name: "Jess", image: "https://api.blitmap.com/v1/png/61" },
  62: { name: "Lay Off Me", image: "https://api.blitmap.com/v1/png/62" },
  63: { name: "Say What", image: "https://api.blitmap.com/v1/png/63" },
  64: { name: "Cool Cat", image: "https://api.blitmap.com/v1/png/64" },
  65: { name: "Eggplant", image: "https://api.blitmap.com/v1/png/65" },
  66: { name: "Sasquatch", image: "https://api.blitmap.com/v1/png/66" },
  67: { name: "Mushroom", image: "https://api.blitmap.com/v1/png/67" },
  68: { name: "Dunce", image: "https://api.blitmap.com/v1/png/68" },
  69: { name: "Soft", image: "https://api.blitmap.com/v1/png/69" },
  70: { name: "End", image: "https://api.blitmap.com/v1/png/70" },
  71: { name: "Embryo", image: "https://api.blitmap.com/v1/png/71" },
  72: { name: "Watching", image: "https://api.blitmap.com/v1/png/72" },
  73: { name: "News", image: "https://api.blitmap.com/v1/png/73" },
  74: { name: "Caffeinate", image: "https://api.blitmap.com/v1/png/74" },
  75: { name: "Communion", image: "https://api.blitmap.com/v1/png/75" },
  76: { name: "Din-Din", image: "https://api.blitmap.com/v1/png/76" },
  77: { name: "Warm Vibe", image: "https://api.blitmap.com/v1/png/77" },
  78: { name: "The Guy", image: "https://api.blitmap.com/v1/png/78" },
  79: { name: "Reset", image: "https://api.blitmap.com/v1/png/79" },
  80: { name: "Key", image: "https://api.blitmap.com/v1/png/80" },
  81: { name: "Glimpse", image: "https://api.blitmap.com/v1/png/81" },
  82: { name: "Boysdocry", image: "https://api.blitmap.com/v1/png/82" },
  83: { name: "Wave", image: "https://api.blitmap.com/v1/png/83" },
  84: { name: "Logo", image: "https://api.blitmap.com/v1/png/84" },
  85: { name: "Melt Man", image: "https://api.blitmap.com/v1/png/85" },
  86: { name: "Cherrybomb", image: "https://api.blitmap.com/v1/png/86" },
  87: { name: "Melony", image: "https://api.blitmap.com/v1/png/87" },
  88: { name: "Fishy", image: "https://api.blitmap.com/v1/png/88" },
  89: { name: "Watcher", image: "https://api.blitmap.com/v1/png/89" },
  90: { name: "Glitcho", image: "https://api.blitmap.com/v1/png/90" },
  91: { name: "City", image: "https://api.blitmap.com/v1/png/91" },
  92: { name: "Exe", image: "https://api.blitmap.com/v1/png/92" },
  93: { name: "Sock Cloud", image: "https://api.blitmap.com/v1/png/93" },
  94: { name: "Gate", image: "https://api.blitmap.com/v1/png/94" },
  95: { name: "Optimist", image: "https://api.blitmap.com/v1/png/95" },
  96: { name: "Pale Tower", image: "https://api.blitmap.com/v1/png/96" },
  97: { name: "Drink Me", image: "https://api.blitmap.com/v1/png/97" },
  98: { name: "Chaos Flow", image: "https://api.blitmap.com/v1/png/98" },
  99: { name: "Lost Realm", image: "https://api.blitmap.com/v1/png/99" },
};
