export const blitmap: { name: string; image: string }[] = [
  { name: "Genesis", image: "https://api.blitmap.com/v1/png/0" },
  { name: "Rose", image: "https://api.blitmap.com/v1/png/1" },
  { name: "Boombox", image: "https://api.blitmap.com/v1/png/2" },
  { name: "Node", image: "https://api.blitmap.com/v1/png/3" },
  { name: "Psychic", image: "https://api.blitmap.com/v1/png/4" },
  { name: "Ikura", image: "https://api.blitmap.com/v1/png/5" },
  { name: "Edition", image: "https://api.blitmap.com/v1/png/6" },
  { name: "Selected", image: "https://api.blitmap.com/v1/png/7" },
  { name: "Kraken", image: "https://api.blitmap.com/v1/png/8" },
  { name: "Totally", image: "https://api.blitmap.com/v1/png/9" },
  { name: "Looney", image: "https://api.blitmap.com/v1/png/10" },
  { name: "Atlantis", image: "https://api.blitmap.com/v1/png/11" },
  { name: "Otoro", image: "https://api.blitmap.com/v1/png/12" },
  { name: "Jupiter", image: "https://api.blitmap.com/v1/png/13" },
  { name: "Overloaded", image: "https://api.blitmap.com/v1/png/14" },
  { name: "Mask", image: "https://api.blitmap.com/v1/png/15" },
  { name: "Vanilla", image: "https://api.blitmap.com/v1/png/16" },
  { name: "Tamago", image: "https://api.blitmap.com/v1/png/17" },
  { name: "The Cat", image: "https://api.blitmap.com/v1/png/18" },
  { name: "Ebi", image: "https://api.blitmap.com/v1/png/19" },
  { name: "Eruption", image: "https://api.blitmap.com/v1/png/20" },
  { name: "Night Moon", image: "https://api.blitmap.com/v1/png/21" },
  { name: "Processing", image: "https://api.blitmap.com/v1/png/22" },
  { name: "The Sun", image: "https://api.blitmap.com/v1/png/23" },
  { name: "Hillside", image: "https://api.blitmap.com/v1/png/24" },
  { name: "Ever Lovin", image: "https://api.blitmap.com/v1/png/25" },
  { name: "Cheese", image: "https://api.blitmap.com/v1/png/26" },
  { name: "Scramble", image: "https://api.blitmap.com/v1/png/27" },
  { name: "Moderator", image: "https://api.blitmap.com/v1/png/28" },
  { name: "Swordy", image: "https://api.blitmap.com/v1/png/29" },
  { name: "Healtreey", image: "https://api.blitmap.com/v1/png/30" },
  { name: "Mageglovey", image: "https://api.blitmap.com/v1/png/31" },
  { name: "Feathery", image: "https://api.blitmap.com/v1/png/32" },
  { name: "Teddy", image: "https://api.blitmap.com/v1/png/33" },
  { name: "Cloudy", image: "https://api.blitmap.com/v1/png/34" },
  { name: "Candy", image: "https://api.blitmap.com/v1/png/35" },
  { name: "Chessbirdy", image: "https://api.blitmap.com/v1/png/36" },
  { name: "Angrybirby", image: "https://api.blitmap.com/v1/png/37" },
  { name: "Burgery", image: "https://api.blitmap.com/v1/png/38" },
  { name: "Periwinkle", image: "https://api.blitmap.com/v1/png/39" },
  { name: "Sprout", image: "https://api.blitmap.com/v1/png/40" },
  { name: "Amai", image: "https://api.blitmap.com/v1/png/41" },
  { name: "Blit", image: "https://api.blitmap.com/v1/png/42" },
  { name: "Rune", image: "https://api.blitmap.com/v1/png/43" },
  { name: "Vibe", image: "https://api.blitmap.com/v1/png/44" },
  { name: "Ride", image: "https://api.blitmap.com/v1/png/45" },
  { name: "Andrei", image: "https://api.blitmap.com/v1/png/46" },
  { name: "Soft Boy", image: "https://api.blitmap.com/v1/png/47" },
  { name: "Pizza Time", image: "https://api.blitmap.com/v1/png/48" },
  { name: "Hot Damn", image: "https://api.blitmap.com/v1/png/49" },
  { name: "Everything", image: "https://api.blitmap.com/v1/png/50" },
  { name: "Illuminate", image: "https://api.blitmap.com/v1/png/51" },
  { name: "Six Months", image: "https://api.blitmap.com/v1/png/52" },
  { name: "Mana", image: "https://api.blitmap.com/v1/png/53" },
  { name: "Nude", image: "https://api.blitmap.com/v1/png/54" },
  { name: "Kabuto", image: "https://api.blitmap.com/v1/png/55" },
  { name: "Mori", image: "https://api.blitmap.com/v1/png/56" },
  { name: "Hand", image: "https://api.blitmap.com/v1/png/57" },
  { name: "Gato", image: "https://api.blitmap.com/v1/png/58" },
  { name: "Ear", image: "https://api.blitmap.com/v1/png/59" },
  { name: "Eye", image: "https://api.blitmap.com/v1/png/60" },
  { name: "Jess", image: "https://api.blitmap.com/v1/png/61" },
  { name: "Lay Off Me", image: "https://api.blitmap.com/v1/png/62" },
  { name: "Say What", image: "https://api.blitmap.com/v1/png/63" },
  { name: "Cool Cat", image: "https://api.blitmap.com/v1/png/64" },
  { name: "Eggplant", image: "https://api.blitmap.com/v1/png/65" },
  { name: "Sasquatch", image: "https://api.blitmap.com/v1/png/66" },
  { name: "Mushroom", image: "https://api.blitmap.com/v1/png/67" },
  { name: "Dunce", image: "https://api.blitmap.com/v1/png/68" },
  { name: "Soft", image: "https://api.blitmap.com/v1/png/69" },
  { name: "End", image: "https://api.blitmap.com/v1/png/70" },
  { name: "Embryo", image: "https://api.blitmap.com/v1/png/71" },
  { name: "Watching", image: "https://api.blitmap.com/v1/png/72" },
  { name: "News", image: "https://api.blitmap.com/v1/png/73" },
  { name: "Caffeinate", image: "https://api.blitmap.com/v1/png/74" },
  { name: "Communion", image: "https://api.blitmap.com/v1/png/75" },
  { name: "Din-Din", image: "https://api.blitmap.com/v1/png/76" },
  { name: "Warm Vibe", image: "https://api.blitmap.com/v1/png/77" },
  { name: "The Guy", image: "https://api.blitmap.com/v1/png/78" },
  { name: "Reset", image: "https://api.blitmap.com/v1/png/79" },
  { name: "Key", image: "https://api.blitmap.com/v1/png/80" },
  { name: "Glimpse", image: "https://api.blitmap.com/v1/png/81" },
  { name: "Boysdocry", image: "https://api.blitmap.com/v1/png/82" },
  { name: "Wave", image: "https://api.blitmap.com/v1/png/83" },
  { name: "Logo", image: "https://api.blitmap.com/v1/png/84" },
  { name: "Melt Man", image: "https://api.blitmap.com/v1/png/85" },
  { name: "Cherrybomb", image: "https://api.blitmap.com/v1/png/86" },
  { name: "Melony", image: "https://api.blitmap.com/v1/png/87" },
  { name: "Fishy", image: "https://api.blitmap.com/v1/png/88" },
  { name: "Watcher", image: "https://api.blitmap.com/v1/png/89" },
  { name: "Glitcho", image: "https://api.blitmap.com/v1/png/90" },
  { name: "City", image: "https://api.blitmap.com/v1/png/91" },
  { name: "Exe", image: "https://api.blitmap.com/v1/png/92" },
  { name: "Sock Cloud", image: "https://api.blitmap.com/v1/png/93" },
  { name: "Gate", image: "https://api.blitmap.com/v1/png/94" },
  { name: "Optimist", image: "https://api.blitmap.com/v1/png/95" },
  { name: "Pale Tower", image: "https://api.blitmap.com/v1/png/96" },
  { name: "Drink Me", image: "https://api.blitmap.com/v1/png/97" },
  { name: "Chaos Flow", image: "https://api.blitmap.com/v1/png/98" },
  { name: "Lost Realm", image: "https://api.blitmap.com/v1/png/99" },
];
