[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../blitoadz-contracts"

[context.production]
  environment = { REACT_APP_CHAIN_ID = "1", REACT_APP_NETWORK = "mainnet" }

[context.staging]
  environment = { REACT_APP_CHAIN_ID = "4", REACT_APP_NETWORK = "rinkeby" }
